### PR TITLE
Sam dev fixes

### PR DESCRIPTION
**Pull request by Sam-Tygier**
Changes to exceptions to make them more like the standard library.

Fix warnings due to changes in implicit constructors in C++11

### CODE REVIEW

**Comment by Sam-Tygier** [comment]
Note that this and #43 both touch APIChanges.md. Whichever is merged first, the other will probably need me to rebase.

**Comment by Sam-Tygier** [comment]
That was messy. Let me try another method.

**Comment by Sam-Tygier** [comment]
Better. Ready to merge.

**Review by scottmrowan — APPROVED** [review]

**Comment by Sam-Tygier** [comment]
Thanks

**Pull request merged**
