### PR TITLE
Arm fixes

### PR DESCRIPTION
**Pull request by Sam-Tygier**
Fixes to allow tests to pass on a raspberrypi2

### CODE REVIEW

**Comment by JamesMolson** [comment]
That isn't the current best way to change the test timeout afaik.

**Comment by Sam-Tygier** [comment]
I also tried CTEST_TEST_TIMEOUT but it does not have any effect. It seems like DART_TESTING_TIMEOUT is what is used by ctest. Or do you mean that we should not be hardwiring it in based on the cpu arch?

**Comment by JamesMolson** [comment]
set_tests_properties(${TST} PROPERTIES TIMEOUT "172800")

gives you 48 hours.

**Comment by Sam-Tygier** [comment]
I think its actually the test name, we have multiple tests that call the same executable with different arguments. So to do this without being very verbose would require wrapping a macro around add_test(). Is there any documentation over why this is better than DART_TESTING_TIMEOUT?

**Comment by Sam-Tygier** [comment]
i'll merge the template patch for now, so that i get builds on raspberrypi

**Comment by Sam-Tygier** [comment]
https://github.com/MERLIN-Collaboration/MERLIN/pull/8

**Pull request closed without merging**
