### PR TITLE
Add + load Interpolated Octagon apertures.

### PR DESCRIPTION
**Pull request by JamesMolson**
Also deal with situations where bad things can happen by setting a default aperture class.

### CODE REVIEW

**Comment by Sam-Tygier** [comment]
I've not checked math for the PointInside function, but it looks similar enough to the existing oct aperture. Seems a little odd that there is no 'OR' when checking the diagonal case.

It would be nice if there was a test for it. It could be added to aperture_test.cpp, unless you want to split each shape into a separate test.

I can merge now, or wait for some tests.

**Comment by JamesMolson** [comment]
where should there be an or?


And yes merge please. I'm going to split up all the aperture tests into their own units, and add some for each possible type.

**Comment by Sam-Tygier** [comment]
There are 4 variables defining the octagon, so I'd expect 4 boundaries to be checked (with some fabs to cover the symmetry). But between the 'ifs' it looks like only 3 boundaries are checked. So either there is some trick in the maths that I have not spotted, or the 4 variables do not correspond to what I expect (distance of each boundary from the origin).

`if(x >= hw || y >= hh)`
...
`if(cc1*(y - cc2) - cc3*(x - hw) <= 0 )`

**Comment by JamesMolson** [comment]
top, size, and the diagonal? the rest is symmetric, the fabs pushes it all into one quadrant?

**Comment by Sam-Tygier** [comment]
I was assuming 4 lengths, with 2-fold rotational symetry, like


I now see that SimpleApertures.h has 2 lengths and 2 angles, but its not clear which angles.

**Comment by JamesMolson** [comment]
The lengths are 1 and 2 there, but the angles are to the vertices in the upper right quadrant.

http://cern.ch/madx/releases/last-dev/madxuguide.pdf

**Comment by Sam-Tygier** [comment]
Something like:

**Comment by JamesMolson** [comment]
yes

**Comment by Sam-Tygier** [comment]
ok. makes more sense now.

**Pull request merged**
